### ISSUE TITLE
Usage with `DataTemplateSelector` results in `LayoutCycleException`

### ISSUE THREAD

**Issue by daltzctr** [MPowerKit/VirtualizeListView#11]
Reproduced on Windows

Reproduction:
1. Create a `VirtualizeListView` with an ItemsSource binded to a `List<object>`
2. Create a DataTemplateSelector that selects views based on object type (or you could have fixed objects, this is just what I have in production)
3. Set `ItemTemplate` of `VirtualizeListView` to the `DataTemplateSelector` you created.
4. Run, observe crash. If you break point in `OnSelectTemplate`, you can observe that duplicate `DataTemplates` are being created for some reason. Substituting the `VirtualizeListView` for a `CollectionView` results in no crash.

**Comment by Alex-Dobrynin** [comment]
@daltzctr I have a very busy schedule. so please, when you creating an issue, please provide a repro project as zip file

**Comment by Alex-Dobrynin** [comment]
Also, I'm using this listview in my production projects with TemplateSelectors almost everywhere in the apps, no crashes. I suppose you missing smth

**Comment by Alex-Dobrynin** [comment]
Closing this issue for now, until you provide repro, then will reopen
