### ISSUE TITLE
VirtualizeListView contents disappear when changing monitors of different DPI

### ISSUE THREAD

**Issue by daltzctr** [MPowerKit/VirtualizeListView#12]
Symptoms:
- Content disappears or gets cut off when changing between Windows of different DPI

Reproduction:
- Create a `VirtualizeListView`, populate with contents
- Drag application between monitors, one set to 100% scaling, the other set to 150% scaling.
- Observe content disappear.

Reproduction Repo: Pending

https://github.com/user-attachments/assets/d6523a89-c86b-434f-98cf-8a5b76d03023

**Comment by Alex-Dobrynin** [comment]
Just tried to reproduce, but everything works as expected. Used Sample project from this repo

**Comment by Daltz333** [comment]
I forgot to add that my monitors are also different resolutions.

**Comment by Alex-Dobrynin** [comment]
@daltzctr please try v 1.2.0
