### ISSUE TITLE
Bugs after updation Mpowerkit.virtualizelisview to 1.1.7

### ISSUE THREAD

**Issue by haideralifaizi** [MPowerKit/VirtualizeListView#13]
I have updated to latest version 1.1.7 but list becomes laggy and also not smooth. Also, one more thing that when i update element of the list, there are wrong elements show. Then, I upgrade down to 1.1.6 version, it becomes very fast as always everything scrolling, etc. Can you fix that issues that in 1.1.7 version because scrolling becomes slow, crash on updation of whole item and many bugs?

**Comment by haideralifaizi** [comment]
Thanks

**Comment by Alex-Dobrynin** [comment]
Ok, so for this issue I have to completely redesign render engine and it can take some time. I've already did some investigations and pushed them to separate branch, but I have to reject previous render of the items, that was just as changing items translation (which is virtual change) to ```view.Arrange()``` at least for android

**Comment by Alex-Dobrynin** [comment]
Just released v 1.2.0 https://github.com/MPowerKit/VirtualizeListView/pull/14
