### ISSUE TITLE
Horizontal Width issues and cache issue

### ISSUE THREAD

**Issue by haideralifaizi** [MPowerKit/VirtualizeListView#17]
When I use this list, list does not occupies full width. It first compress, then, it has been fixed. Even I used horizontal option to fillandexpand and even grid to Rowdefinition="auto,*". One solution is to set width or use any thing that we set width but it is not good solution. Can you fix that issue and also add new option for disabling and enabling cache. It works fine in some cases and does not in some cases

**Comment by Alex-Dobrynin** [comment]
Provide Repro project please. Without it, I cannot help you

**Comment by Alex-Dobrynin** [comment]
please try v2.0.0-pre, maybe this is fixed in that version

**Comment by haideralifaizi** [comment]
> please try v2.0.0-pre, maybe this is fixed in that version

It has been fixed in that version. Thanks bro 😊😊
