### ISSUE TITLE
Grouped Example or Documentation Needed

### ISSUE THREAD

**Issue by tbaggett** [MPowerKit/VirtualizeListView#18]
Hello, thanks so much for sharing your library! I'm really hopeful it will solve the item resizing problems I've had with other List/Collection view components.

I need a header, footer, and group headers with grouping enabled in my use case. I didn't see an example of grouping used in the sample code or explained in your documentation. Do you have an existing example you can share?

Also, I'm confused by having to assign to both the Header/Footer and HeaderTemplate/FooterTemplate properties as raised in issue #1. 

I don't know if I set it up correctly, but I assigned a data template to the HeaderTemplate property in the XAML, then added the code below where I'm trying to use the control. The header content shows up, but it's data binding is broken, so it isn't displayed correctly.

Constructor:

```
        InitializeComponent();

        VirtualizedListView.Header = VirtualizedListView.HeaderTemplate?.CreateContent();
        VirtualizedListView.Footer = VirtualizedListView.FooterTemplate?.CreateContent();
```

OnBindingContextChanged:

```
    protected override void OnBindingContextChanged()
    {
        base.OnBindingContextChanged();
    
        if (VirtualizedListView.Header is VisualElement header)
        {
            header.BindingContext = BindingContext;
        }
    
        if (VirtualizedListView.Footer is VisualElement footer)
        {
            footer.BindingContext = BindingContext;
        }
    }
```

**Comment by Alex-Dobrynin** [comment]
Hi, thanks for mentioning this. Yes, It will solve your issues with cells resizing on each platform. Also, I will add docs for header/footers/grouping, but in a future release which will bring Grid items layout.

But for now, if you need to add groups, your `ItemsSource` has to be `typeof(IEnumerable<IEnumerable<>>)`, then you need to set `IsGrouping="True"` on listview and you need to add Group Header/Footer templated as next:

```xaml
<mpowerkit:VirtualizeListView.GroupHeaderTemplate>
    <DataTemplate x:DataType="YourGroupType">
        <Grid Padding="15"
              BackgroundColor="Aqua">
            <Label Text="{Binding Key}" />
        </Grid>
    </DataTemplate>
</mpowerkit:VirtualizeListView.GroupHeaderTemplate>
```

**Comment by tbaggett** [comment]
Thanks for the quick reply! 

So I see now, the Header and Footer properties are the binding context for the views that are created from the assigned HeaderTemplate and FooterTemplate. That is what I misunderstood. Thank you for clarifying that.
