### ISSUE TITLE
Setting Orientation="Horizontal" crashes on windows.

### ISSUE THREAD

**Issue by PCDK** [MPowerKit/VirtualizeListView#19]
If you set `Orientation="Horizontal"` on the **VirtualizeListView** it will crash when you set an **ItemsSource**.
This does not happen on Android. I have not tested iOS.
I tested with the previous version (1.25) and that seems to work fine.

[TestListCrash.zip](https://github.com/user-attachments/files/16808579/TestListCrash.zip)

**Comment by Alex-Dobrynin** [comment]
Yes, can reproduce

**Comment by Alex-Dobrynin** [comment]
fixed in v2.0.1
