### ISSUE TITLE
Grid items layout 

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [MPowerKit/VirtualizeListView#2]
Your project is very good.

Do you have any plans for adding the grid layout? I want to use the plugin, but this is essential in my application.

**Comment by Alex-Dobrynin** [comment]
Unfortunately at the moment I don't have time to implement Grid layout. but this is in plans. If you have ideas how to implement it and have desire and time, you may create a PR, I will appreciate this.

**Comment by andersonvieiragomeslopes** [comment]
> Unfortunately at the moment I don't have time to implement Grid layout. but this is in plans. If you have ideas how to implement it and have desire and time, you may create a PR, I will appreciate this.

I have no idea how to do this lol, I was hoping you knew and could even indicate the way for me to make a PR myself, your plugin is extremely useful, but without the grid layout it is bad for my project, I I'm going to investigate how this is done in Maui's collectionview to try to replicate it here.

**Comment by Alex-Dobrynin** [comment]
You will not find this in MAUI repo, because MAUI's CollectionView using native implementation of GridLayout for each platform.

**Comment by Alex-Dobrynin** [comment]
if you want to know how gridlayout is implemented you better look into source code of android's GridLayoutManager
