### ISSUE TITLE
iPadOS VirtualizeListView doesn't resize after orientation change

### ISSUE THREAD

**Issue by tbaggett** [MPowerKit/VirtualizeListView#20]
Hello and thanks again for such a great library of components!

I ran across a small thing that I solved but want to share in case you want to address it or for others who need it if not.

When using VirtualListView as a child of FixedRefreshView on iPads, the VLV content (header, footer, items etc.) isn't resized when rotating the device. 

It works as expected if the VLV component is not a child of the FixedRefreshView component. 

This may also occur on iOS/iPhones. I haven't tested that as the app I'm using the component in only supports free rotation on tablets.

I reviewed the FixedRefreshView source and see that you add a SizeChanged listener when running on Android at https://github.com/MPowerKit/VirtualizeListView/blob/2ed8e74ad99d41ec4cd0a442eec557ee4e6df7e4/MPowerKit.VirtualizeListView/FixedRefreshView.cs#L16

I extended the FixedRefreshView class and added the same code but checking for IOS being defined. It resolved the issue for me. So the size changed code is needed for both Android and iOS.

I hope this helps someone!

**Comment by Alex-Dobrynin** [comment]
Just double checked everything and it seems to me that after screen rotation everything was recalculated and size changed.
Please be sure you are using the latest one nuget.
Also, I found another one bug on iOS for iPhones and tablets, this is bug of MAUI platform when screen rotated and size of the VLV changed the underlying items layout gets wrong dimensions to the `Measure` method and thus calculates wrong items layout size. i just fixed it, also added ios precondition to the fixed refreshview. hope this helps in your case.
