### ISSUE TITLE
[Question] Getting `FirstVisibleItemIndex`

### ISSUE THREAD

**Issue by angrynerds-krzysztof** [MPowerKit/VirtualizeListView#3]
Is it possible to get `FirstVisibleItemIndex` as in the CollectionView control? :)

**Comment by Alex-Dobrynin** [comment]
Implemented in 1.1.0
Use GetAllVisibleItems on VirtualizeListView.
Note: I dont reccomend you to use it each time the collection scrolls, or at least do it in BG thread

**Comment by angrynerds-krzysztof** [comment]
Thank you!

**Comment by angrynerds-krzysztof** [comment]
You do a great job!

**Comment by angrynerds-krzysztof** [comment]
@Alex-Dobrynin  Is it possible to use something like `EmptyView` with your control or just extend your control by myself?

**Comment by Alex-Dobrynin** [comment]
the answer is here
https://github.com/MPowerKit/VirtualizeListView/issues/4#issuecomment-2230596864
